module.exports = {
  disabled: false,
  provider: "microsoft-graph",
  tenantId: "YOUR_MICROSOFT_TENANT_ID",
  clientId: "YOUR_MICROSOFT_APP_CLIENT_ID",
  clientSecret: "YOUR_MICROSOFT_APP_CLIENT_SECRET",
  from: "artwork3@giftwrap.co.za",
  senderName: "Logistics Centre",
  to: "admin3@giftwrap.co.za",
  artworkTo: "artwork3@giftwrap.co.za",
  adminActionTo: "admin3@giftwrap.co.za",
  rolloverTestTo: "artwork3@giftwrap.co.za",
  droppedOfficeSsTo: "Sheryl-ann@giftwrap.co.za",
  droppedOfficeSbTo: "reception@giftwrap.co.za",
  droppedOfficeMorMarTo: "promo22@giftwrap.co.za",
  droppedOfficeOrderTo: "orders@giftwrapshop.co.za",
  droppedOfficeFallbackTo: "order@giftwrapshop.co.za",
};
